### ISSUE TITLE
leadAccountId format

### ISSUE THREAD

**Issue by Mooey28** [tenable/integration-jira-cloud#10]
The example config.yaml file states that it needs a lead account ID for the project, and gives it in the format 554433:00112233-ffee-aabb-aabb-998877665544. I've tried everywhere both in the Jira UI and running GETs on the project itself to return the leadaccountID but each way it does not return any ID in that format. All I've got is a 24-character alphanumeric string, and plugging this into the config.yaml file just returns the following error output. I also note that it says no project with key VMNGT - I have added that into the config.yaml file because VULN is already the name of a project. I'd have assumed the setup should spot that I haven't also create VMNGT and try and create this...?

```
C:\Program Files\Python37\Scripts>tenable-jira.exe tenable-jira-config.yaml --setup-only
2020-02-17 14:46:08,003 restfly.errors.NotFoundError ERROR [404: GET] https://xxx.atlassian.net/rest/api/3/project/VMNGT body=b'{"errorMessages":["No project could be found with key \'VMNGT\'."],"errors":{}}'
2020-02-17 14:46:08,112 restfly.errors.BadRequestError ERROR [400: POST] https://xxx.atlassian.net/rest/api/3/project body=b'{"errorMessages":[],"errors":{"projectLead":"You must specify a valid project lead."}}'
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tenable_jira\jira\projects.py", line 32, in upsert
    return self.details(kwargs['key'])
  File "c:\program files\python37\lib\site-packages\tenable_jira\jira\projects.py", line 9, in details
    return self._api.get('project/{}'.format(id), params=kwargs).json()
  File "c:\program files\python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 408, in get
  File "c:\program files\python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 376, in _request
restfly.errors.NotFoundError: [404: GET] https://xxx.atlassian.net/rest/api/3/project/VMNGT body=b'{"errorMessages":["No project could be found with key \'VMNGT\'."],"errors":{}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\tenable-jira-script.py", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.0', 'console_scripts', 'tenable-jira')()
  File "c:\program files\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\tenable_jira\cli.py", line 100, in cli
    ingest = Tio2Jira(source, jira, config)
  File "c:\program files\python37\lib\site-packages\tenable_jira\transform.py", line 19, in __init__
    self._project = self._jira.projects.upsert(**config['project'])
  File "c:\program files\python37\lib\site-packages\tenable_jira\jira\projects.py", line 34, in upsert
    return self.create(**kwargs)
  File "c:\program files\python37\lib\site-packages\tenable_jira\jira\projects.py", line 28, in create
    return self._api.post('project', json=kwargs).json()
  File "c:\program files\python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 429, in post
  File "c:\program files\python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 376, in _request
restfly.errors.BadRequestError: [400: POST] https://xxx.atlassian.net/rest/api/3/project body=b'{"errorMessages":[],"errors":{"projectLead":"You must specify a valid project lead."}}'
```

**Comment by Mooey28** [comment]
Upon further trial and error, looks like the leadAccountID in the 24-character format does work, and it was infact the username that was incorrect. For reference, doesn't look like it accepts the full email address as the username, and just the user portion of the email address. My next issue is that I now get 401 and 403 errors, which seem to then relate to it trying to log in to Jira and getting access issues - again strange given in postman the API key (with the email address for the username) works absolutely fine and can log in but in this integration it errors... I'll do some more investigation within my means and raise any further issues if I find any.

**Comment by SteveMcGrath** [comment]
I'm willing to bet this is dependent on how the instance is configured.
