### ISSUE TITLE
Errors while integrating with Jira cloud

### ISSUE THREAD

**Issue by razsh63** [tenable/integration-jira-cloud#118]
while I'm trying to integrate Tenable.io with Jira, experiencing the attached errors can someone please help?

1) tenable-jira `config.yaml`

```
"expected <block end>, but found %r" % token.id, token.start_mark)

yaml.parser.ParserError: while parsing a block mapping

 in "config.yaml", line 1, column 1

expected <block end>, but found '<scalar>'
```

 in "config.yaml", line 6, column 3

2) tenable-jira -f -v $(date -v-1d +%s) config.yaml

```
date: invalid option -- 'v'

Try 'date --help' for more information.

Usage: tenable-jira [OPTIONS] [CONFIGFILE]

Try 'tenable-jira --help' for help.
```
![image](https://user-images.githubusercontent.com/84676552/119531886-fe5faf00-bda1-11eb-83bc-1a95217ed013.png)

**Comment by razsh63** [comment]
Now stuck here

`tenable-jira ~/jira-cloud/jira_c                                                                                        loud_config.yaml
Traceback (most recent call last):
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/bin/tenable-jira", line 11, in                                                                                         <module>
    load_entry_point('tenable-jira-cloud==1.1.23', 'console_scripts', 'tenable-j                                                                                        ira')()
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/lib64/python3.6/dist-packages/                                                                                        click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/lib64/python3.6/dist-packages/                                                                                        click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/lib64/python3.6/dist-packages/                                                                                        click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/lib64/python3.6/dist-packages/                                                                                        click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/jira-cloud/jira-cloud-venv/lib64/python3.6/dist-packages/                                                                                        tenable_jira/cli.py", line 72, in cli
    if config['tenable'].get('tio_transform_tags'):
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by SteveMcGrath** [comment]
can you please post your config?  it looks like there may be a formatting issue.

**Comment by SteveMcGrath** [comment]
Closing from lack of response
