### ISSUE TITLE
KeyError: 'token' error

### ISSUE THREAD

**Issue by rayl7786** [tenable/integration-jira-cloud#120]
I am not sure what may be happening here, looking at the code, it may do something with how it POSTs the token but not sure. I have debug mode enabled
`# tenable-jira config.yaml
Traceback (most recent call last):
  File "/root/jira-cloud/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.23', 'console_scripts', 'tenable-jira')()
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable_jira/cli.py", line 140, in cli
    build=__version__
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 268, in __init__
    secret_key=secret_key)
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 319, in login
    'X-SecurityCenter': str(resp.json()['response']['token'])
KeyError: 'token'
`

In the logfile I added in the config.yaml and set to debug level, all I get is this
`2021-05-26 12:20:27,516 root INFO Tenable2JiraCloud Version 1.1.23
2021-05-26 12:20:27,516 root INFO Using configuration file config.yaml
2021-05-26 12:20:27,516 root INFO Running on Python 3.6.8 Linux/x86_64
2021-05-26 12:20:27,517 tenable.sc.TenableSC DEBUG {"method": "GET", "url": "https://tenable.example.com:443/rest/system", "params": {}, "body": {}}
2021-05-26 12:20:27,521 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): tenable.example.com:443
2021-05-26 12:20:27,612 urllib3.connectionpool DEBUG https://tenable.example.com:443 "GET /rest/system HTTP/1.1" 200 None
2021-05-26 12:20:27,615 tenable.sc.TenableSC DEBUG {"method": "POST", "url": "https://tenable.example.com:443/rest/token", "params": "REDACTED", "body": "REDACTED"}
2021-05-26 12:20:27,724 urllib3.connectionpool DEBUG https://tenable.example.com:443 "POST /rest/token HTTP/1.1" 200 121
`

I changed the URL on purpose but it is a valid URL

**Comment by SteveMcGrath** [comment]
Can you please use API Keys instead of username/password?

**Comment by rayl7786** [comment]
I did use API Keys. I created my Tenable SC access_key and secret_key. On Jira Cloud, I created an API token, I still get the KeyError: 'token' error. I followed a Tenable SC configuration template

**Comment by SteveMcGrath** [comment]
can you post your config (redacted of course)

**Comment by rayl7786** [comment]
`tenable:
  platform: tenable.sc
  address: tenable.example.com
  query_id: 4275
  access_key: 68fc62...
  secret_key: 43a231....

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: PXokI....

  # The User that will be authenticaing to the Jira application
  api_username: rleon@example.com

  # The address pointing to the Jira application.
  address: example.atlassian.net

project:
  # The lead account id for the primary user for the project.
  leadAccountId: 5f5a3ad...
  key: TSC

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: debug

  # If you would like the log output to goto a file instead of standard output,
  # then specify the filename here:
  filename: /var/log/syslog

# The following section is optional.  You should only specify this section if
# you would like the bridge to run as a service with it's own timer.
service:
  # How many hours should we wait between jobs?  Note setting this to a
  # non-zero number will result in imports past the initial import will use
  # time of the last completed import as the basis for last observed.
  interval: 24
`

**Comment by SteveMcGrath** [comment]
I cannot seem to replicate the issue.  Can you please paste the traceback?

It should look similar to this:

```
Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/jira_cloud/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud', 'console_scripts', 'tenable-jira')()
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/steve/Dropbox/Repositories/integrations/jira_cloud/tenable_jira/cli.py", line 140, in cli
    build=__version__
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/tenable/sc/__init__.py", line 268, in __init__
    secret_key=secret_key)
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/tenable/sc/__init__.py", line 316, in login
    'password': password
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/tenable/base/v1.py", line 592, in post
    return self._request('POST', path, **kwargs)
  File "/Users/steve/.pyenv/versions/3.7.3/envs/jira_cloud/lib/python3.7/site-packages/tenable/base/v1.py", line 545, in _request
    raise self._error_codes[status](resp)
tenable.errors.APIError: None:403 {"type":"regular","response":[],"error_code":161,"error_msg":"Invalid login credentials.\n","warnings":[],"timestamp":1622564760}
```

**Comment by rayl7786** [comment]
`Traceback (most recent call last):
  File "/root/jira-cloud/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.23', 'console_scripts', 'tenable-jira')()
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/jira-cloud/lib64/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable_jira/cli.py", line 140, in cli
    build=__version__
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 268, in __init__
    secret_key=secret_key)
  File "/root/jira-cloud/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 319, in login
    'X-SecurityCenter': str(resp.json()['response']['token'])
KeyError: 'token'
`

**Comment by SteveMcGrath** [comment]
That response tells me a few things that doesn't make sense:

1. The TenableSC package was fed something that makes it think to use session auth (username/password) instead of API Keys
2. The response from /rest/token on the Tenable.sc instance isn't a valid SC response.
3. The API Keys you're passing in the config aren't being passed into the TenableSC package at all.

What concerns me with all of this is that the TenableSC package being used is from pyTenable, is heavily battle tested, and I cannot replicate your response.

Can you attempt to use the username and password fields, and comment out the API Keys, and see what happens?

**Comment by rayl7786** [comment]
So instead of using a virtual environment, I just installed tenable-jira integration on the main environment and everything seems to work just fine with the same config.yaml file. Not sure what it was. I have another issue but will possibly open a separate issue for that. Thank you for your help and time.

**Comment by SteveMcGrath** [comment]
alrighty then, so some weird environmental fun ;)
