### ISSUE TITLE
Unsupported content from Tenable cannot POST into Jira

### ISSUE THREAD

**Issue by Mooey28** [tenable/integration-jira-cloud#13]
Error during script run stating unsupported content trying to be POSTed into Jira.

```
C:\Program Files\Python37\Scripts>tenable-jira.exe tenable-jira-config.yaml
2020-02-19 15:46:19,216 restfly.errors.BadRequestError ERROR [400: POST] https://xxx.atlassian.net/rest/api/3/issue?update_history=False body=b'{"errorMessages":["We can\'t create this issue for you right now, it could be due to unsupported content you\'ve entered into one or more of the issue fields. If this situation persists, contact your administrator as they\'ll be able to access more specific information in the log file."],"errors":{}}'
Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\tenable-jira-script.py", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.0', 'console_scripts', 'tenable-jira')()
  File "C:\Program Files\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\cli.py", line 104, in cli
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\transform.py", line 432, in ingest
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\transform.py", line 388, in create_issues
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\transform.py", line 329, in _process_open_vuln
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\jira\issues.py", line 48, in upsert
  File "C:\Program Files\Python37\lib\site-packages\tenable_jira_cloud-1.1.0-py3.7.egg\tenable_jira\jira\issues.py", line 20, in create
  File "C:\Program Files\Python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 429, in post
  File "C:\Program Files\Python37\lib\site-packages\restfly-1.1.1-py3.7.egg\restfly\session.py", line 376, in _request
restfly.errors.BadRequestError: [400: POST] https://xxx.atlassian.net/rest/api/3/issue?update_history=False body=b'{"errorMessages":["We can\'t create this issue for you right now, it could be due to unsupported content you\'ve entered into one or more of the issue fields. If this situation persists, contact your administrator as they\'ll be able to access more specific information in the log file."],"errors":{}}'
```

I will come back with further debug or Jira logs if I can find them.

**Comment by SteveMcGrath** [comment]
Thanks.  without debugs I cant troubleshoot.

**Comment by Mooey28** [comment]
So the vulnerability it's trying to POST into Jira relates to plugin ID 42411 - Microsoft Windows SMB Shares Unprivileged Access. It looks like one of our instances of this issue has an Output field in Tenable of over 55,000 characters, which means including vulnerability description when adding this into Jira's "Description" field is over 3,000 lines. I don't know if there is a field character or line limit in Jira, do you?

As an aside, would it be sensible to split Vulnerability Description, Solution and Output into separate Jira fields - and perhaps Output itself could be uploaded as an attachment to the relevant sub-task for each asset?

**Comment by Mooey28** [comment]
I found a few Jira Cloud Feature Requests regarding max field length:
https://jira.atlassian.com/browse/JRACLOUD-63007
https://jira.atlassian.com/browse/JRACLOUD-64351
https://jira.atlassian.com/browse/JRACLOUD-63935

Looks like the max length of a field is 32767 characters. So my recommendation would firstly be having vulnerability description, solution and output split into separate custom fields, to initially help counter any edge cases (and may help on further data exporting also) and then look at perhaps firstly throwing a warning in the script to highlight that it couldn't create an issue in Jira and then continuing (rather than exiting out the script run) and then.... looking into uploading the Output as an attachment instead? This one might be a bigger ask and perhaps made easier when (or dare I say if) Atlassian resolve some of those Feature Requests above.

**Comment by SteveMcGrath** [comment]
Generally the offender here is the plugin output.  I think the right move is to trim the output to 10k characters to avoid this issue.

**Comment by SteveMcGrath** [comment]
Truncation has been added and is optionally configurable.  it applies to the paragraph, not to the whole, as Jira uses this really odd format for multi-paragraph content.

As for pushing a file for the output, I think that may be out of scope for this one.  With the content limitations, it may make more sense to just login to the appropriate console instead and view the data there.

As I assume that the max length is should resolve this issue, I will close this at this point.  If the issue persists, please re-open and update.
