### ISSUE TITLE
AttributeError: 'VersionInfo' object has no attribute 'match'

### ISSUE THREAD

**Issue by dil-ddsouza** [tenable/integration-jira-cloud#138]
Hi Steve,

We recently started to experience the 500 errors and I saw your comments for issue #131, basically advising the upgrade restfly and upgrade the tenable-jira integration too.

We were using 1.1.9 before. So I upgraded it to 1.2.0 and upgraded restfly too. However I received the following error and was not sure how to proceed or what caused it:
Traceback (most recent call last):
  File "/home/npres.local/ddsouza/Scripts/env/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.2.0', 'console_scripts', 'tenable-jira')()
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/tenable_jira/cli.py", line 140, in cli
    build=__version__
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 268, in __init__
    secret_key=secret_key)
  File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 326, in login
    if semver.VersionInfo.parse(self.version).match('<5.13.0'):
AttributeError: 'VersionInfo' object has no attribute 'match'

The version of python being used is as follows:
Python 3.6.8

Would appreciate your help and advise here please.

Thanks

**Comment by dil-ddsouza** [comment]
Upon further troubleshooting, it looks like it doesn't like it when I add API keys. So if I use username and password within the config.yaml file, it works fine. However when I add API Keys, it throws up the above error.

**Comment by SteveMcGrath** [comment]
what version of pytenable is installed?  the error is in that library:

`File "/home/npres.local/ddsouza/Scripts/env/lib64/python3.6/site-packages/tenable/sc/init.py", line 326, in login`

**Comment by SteveMcGrath** [comment]
did updating the pytenable package help?

**Comment by dil-ddsouza** [comment]
Hi Steve, it did work after that. However I noticed another issue. I will create a separate issue for that
