### ISSUE TITLE
Epic Name Required Error

### ISSUE THREAD

**Issue by gzdyldz** [tenable/integration-jira-cloud#154]
Hi, 

I am trying to integrate our Cloud Tenable with Jira. I basically run the tool with --setup-only option and passed generated_config.yaml to the script. I am getting the error below error saying that Epic Name is required. I could not understand the reason. Could you please have a look?

`2021-12-09 15:33:50,894 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_10011":"Epic Name is required."}}'
2021-12-09 15:33:50,894 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/Users/gozde.yildiz/.local/share/virtualenvs/Desktop-cjnOPP1z/lib/python3.8/site-packages/tenable_jira/transform.py", line 409, in _process_open_vuln
    i = self._jira.issues.upsert(fields=issue, jql=' and '.join(jql))
  File "/Users/gozde.yildiz/.local/share/virtualenvs/Desktop-cjnOPP1z/lib/python3.8/site-packages/tenable_jira/jira/issues.py", line 48, in upsert
    issue = self.create(**kwargs)
  File "/Users/gozde.yildiz/.local/share/virtualenvs/Desktop-cjnOPP1z/lib/python3.8/site-packages/tenable_jira/jira/issues.py", line 18, in create
    return self._api.post('issue',
  File "/Users/gozde.yildiz/.local/share/virtualenvs/Desktop-cjnOPP1z/lib/python3.8/site-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "/Users/gozde.yildiz/.local/share/virtualenvs/Desktop-cjnOPP1z/lib/python3.8/site-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_10011":"Epic Name is required."}}'`

**Comment by SteveMcGrath** [comment]
That’s likely because your Jira configuration requires an Epic for the issues to be attached to.  It’s possible to add this with a custom field declaration for the Epic field name and id. You can also specify the value within it.

https://github.com/tenable/integration-jira-cloud/issues/141
