### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kamalmudgal1** [tenable/integration-jira-cloud#168]
I am doing the initial integration of tenable.io with jira cloud and I faced this error multiple times, Please help me with this. 

2022-02-18 15:14:59,972 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenable_jira/cli.py", line 156, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "/usr/local/lib/python3.9/site-packages/tenable_jira/transform.py", line 670, in ingest
    self.create_issues(self._src.exports.vulns(**vexport))
  File "/usr/local/lib/python3.9/site-packages/tenable_jira/transform.py", line 529, in create_issues
    self._process_open_vuln(v, fid)
  File "/usr/local/lib/python3.9/site-packages/tenable_jira/transform.py", line 400, in _process_open_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/usr/local/lib/python3.9/site-packages/tenable_jira/transform.py", line 254, in _process_vuln
    'issuetype = "{}"'.format(self.subtask['name']),
TypeError: 'NoneType' object is not subscriptable

Thanks,
Kamal Kumar Mudgal

**Comment by alpesh-te** [comment]
@kamalmudgal1 We are still waiting for more logs and debug
