### ISSUE TITLE
marshmallow.exceptions.ValidationError: {'vpr': ['Unknown field.']}

### ISSUE THREAD

**Issue by alexandr-korotunov-betpawa** [tenable/integration-jira-cloud#187]
Sync from Tenable.io to Jira cloud stops working
```
Traceback (most recent call last):
  File "/usr/local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tenable_jira/cli.py", line 218, in cli
    ingest.ingest(since, first_discovery)
  File "/usr/local/lib/python3.8/dist-packages/tenable_jira/transform.py", line 670, in ingest
    self.create_issues(self._src.exports.vulns(**vexport))
  File "/usr/local/lib/python3.8/dist-packages/tenable/io/exports/api.py", line 453, in vulns
    return self._export('vulns', VulnExportSchema(), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tenable/io/exports/api.py", line 177, in _export
    payload = schema.dump(schema.load(kwargs))
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'vpr': ['Unknown field.']}
```

**Comment by SteveMcGrath** [comment]
whats the config file looking like?

**Comment by alexandr-korotunov-betpawa** [comment]
```
tenable:
  # Tenable.io or API Access Key
  access_key: ****

  # Tenable.io or API Secret Key
  secret_key: ****
  tio_ignore_accepted: true
  tio_autoclose_accepted: true
  tio_vpr_thresh: 7.0
  tio_severities:
    - low
    - medium
    - high
    - critical

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: ****

  # The User that will be authenticaing to the Jira application
  api_username: ***@***.com

  # The address pointing to the Jira application.
  address: ***.atlassian.net
project:
  # The lead account id for the primary user for the project.
  leadAccountId: ****

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: info

  # If you would like the log output to goto a file instead of standard output,
  # then specify the filename here:
  filename: ****

# The following section is optional.  You should only specify this section if
# you would like the bridge to run as a service with it's own timer.
#service:
  # How many hours should we wait between jobs?  Note setting this to a
  # non-zero number will result in imports past the initial import will use
  # time of the last completed import as the basis for last observed.
  #interval: 4
```

**Comment by MitaliUpadhyay** [comment]
Issue is fixed in PR https://github.com/tenable/integration-jira-cloud/pull/201 and the code is merged with master branch.
