### ISSUE TITLE
Asset can't contain spaces

### ISSUE THREAD

**Issue by hamletquid** [tenable/integration-jira-cloud#220]
One of our assets had a whitespace in its name ("users's macbook pro") and this throws the following error:

`2023-03-07 00:39:44,278 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_24933":"The label \'user\'s macbook pro\' can\'t contain spaces."}}'
2023-03-07 00:39:44,279 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 388, in _process_open_vuln
    self._jira.issues.upsert(fields=subissue, jql=' and '.join(sjql))
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 48, in upsert
    issue = self.create(**kwargs)
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 20, in create
    json=kwargs
  File "/home/folder/tenable/lib64/python3.6/site-packages/restfly/session.py", line 639, in post
    return self._req('POST', path, **kwargs)
  File "/home/folder/tenable/lib64/python3.6/site-packages/restfly/session.py", line 546, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_24933":"The label \'user\'s macbook pro\' can\'t contain spaces."}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/cli.py", line 153, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 650, in ingest
    self.create_issues(vulns)
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 498, in create_issues
    self._process_open_vuln(v, fid)
  File "/home/folder/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 391, in _process_open_vuln
    sys.exit(2)
SystemExit: 2`

It seems that this entry is cached somewhere as I get the same error message even after having deleted the asset in both Tenable and Jira.

Any advise on how to get around this is appreciated!

Thanks,
H

**Comment by hamletquid** [comment]
Turned out that Jira throws that error message. Deleting the asset in Tenable "solved" this.
