### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by flakshack** [tenable/integration-jira-cloud#224]
_Including this here in case anyone has the same problem.  This is technically a problem with tenable_jira, not tenable-jira-cloud._  

Attempting to run the scripts for the first time and when it got to the point of connecting to my Tenable instance, I got this error:

```
2023-06-14 14:12:01,426 tenable.sc.TenableSC DEBUG Request: {"method": "GET", "url": "https://<TENABLE_SC_HOST>:443/rest/query/2187?fields=filters", "params": {}, "body": {}}
2023-06-14 14:12:01,458 urllib3.connectionpool DEBUG https://<TENABLE_SC_HOST>:443 "GET /rest/query/2187?fields=filters HTTP/1.1" 200 292
2023-06-14 14:12:01,458 tenable.sc.TenableSC DEBUG Request: {"method": "POST", "url": "https://<TENABLE_SC_HOST>:443/rest/analysis", "params": {}, "body": {"type": "vuln", "sourceType": "cumulative", "query": {"tool": "vulndetails", "type": "vuln", "filters": [{"filterName": "severity", "operator": "=", "value": [{"id": "4", "name": "Critical", "description": "Critical Severity"}, {"id": "3", "name": "High", "description": "High Severity"}]}, {"filterName": "lastSeen", "operator": "=", "value": "0-1686766321"}], "startOffset": 0, "endOffset": 1000}}}
2023-06-14 14:12:02,364 urllib3.connectionpool DEBUG https://<TENABLE_SC_HOST>:443 "POST /rest/analysis HTTP/1.1" 200 None
2023-06-14 14:12:02,411 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "C:\tenable-jira-cloud\Lib\site-packages\tenable_jira\cli.py", line 156, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "C:\tenable-jira-cloud\Lib\site-packages\tenable_jira\transform.py", line 736, in ingest
    self.create_issues(vulns)
  File "C:\tenable-jira-cloud\Lib\site-packages\tenable_jira\transform.py", line 502, in create_issues
    v = flatten(vulnitem)
        ^^^^^^^^^^^^^^^^^
  File "C:\tenable-jira-cloud\Lib\site-packages\tenable_jira\utils.py", line 11, in flatten
    if isinstance(v, collections.MutableMapping):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

A quick search turned up this StackOverflow post:  https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping

I'm running Python 3.11.  In Python 3.10, they moved MutableMapping from "collections" to "collections.abc."

To resolve the issue, I edited **Lib\site-packages\tenable_jira\utils.py** and changed line 11 to:

`        if isinstance(v, collections.abc.MutableMapping):`

After making the change, my first import processed without issue.  Thanks!

**Comment by hdospitia** [comment]
Hello @flakshack. I faced the same issue.

That's a good solution. What I did is to install the package locally instead of use the PIP repo. So I did:

python3 -m pip install -e .
