### ISSUE TITLE
Getting tenable.errors.TioExportsError ERROR vulns export has errored.

### ISSUE THREAD

**Issue by st0ner0ck** [tenable/integration-jira-cloud#225]
After running into several issues that seems to be fixed by manually adding the project, add screens, re-add the custom fields to the screens etc. in Jira we now get:

user@laptop:~/work/scripts/integration-jira-cloud$ tenable-jira test.yaml
Traceback (most recent call last):
  File "/home/user/.local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/tenable_jira/cli.py", line 218, in cli
    ingest.ingest(since, first_discovery)
  File "/home/user/.local/lib/python3.10/site-packages/tenable_jira/transform.py", line 670, in ingest
    self.create_issues(self._src.exports.vulns(**vexport))
  File "/home/user/.local/lib/python3.10/site-packages/tenable_jira/transform.py", line 491, in create_issues
    for vulnitem in vulns:
  File "/home/user/.local/lib/python3.10/site-packages/restfly/iterator.py", line 114, in __next__
    return self.next()  # noqa: PLE1102
  File "/home/user/.local/lib/python3.10/site-packages/tenable/io/exports/iterator.py", line 183, in next
    self._get_page()
  File "/home/user/.local/lib/python3.10/site-packages/tenable/io/exports/iterator.py", line 149, in _get_page
    self._get_chunks()
  File "/home/user/.local/lib/python3.10/site-packages/tenable/io/exports/iterator.py", line 133, in _get_chunks
    status = self._get_status()
  File "/home/user/.local/lib/python3.10/site-packages/tenable/io/exports/iterator.py", line 84, in _get_status
    raise TioExportsError(self.type, self.uuid)
tenable.errors.TioExportsError: vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 has errored.

logfile:

2023-06-26 12:36:20,840 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:36:27,848 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:36:28,120 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:36:28,121 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:36:36,129 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:36:36,309 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:36:36,312 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:36:45,321 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:36:45,525 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:36:45,526 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:36:55,536 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:36:55,708 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:36:55,709 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:37:06,721 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:37:06,899 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:37:06,901 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:37:18,914 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:37:19,088 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:37:19,090 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty PROCESSING
2023-06-26 12:37:32,104 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status", "params": {}, "body": {}}
2023-06-26 12:37:32,291 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/940848eb-e91a-4cfe-9904-b695ca7e0157/status HTTP/1.1" 200 None
2023-06-26 12:37:32,293 tenable.io.exports.iterator.ExportsIterator DEBUG vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 is currenty ERROR
2023-06-26 12:37:32,293 tenable.errors.TioExportsError ERROR vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 has errored.

**Comment by st0ner0ck** [comment]
After checking the other issues I found out there was no data to pull as I've not set the -s parameter.
When doing that I get 1 chunk but am still seeing an error I saw before. What can be wrong when the script does not create the project or screens (I did that manually - only thing the script created was the customfields) and now the script cannot set the screens to the fields even though I can see them in my Jira instance. The screens are associated to the custom fields. 

2023-06-26 13:17:08,085 restfly.errors.BadRequestError ERROR [400: POST] https://redacted.atlassian.net/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_10038":"Field \'customfield_10038\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10039":"Field \'customfield_1       │ 0039\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10042":"Field \'customfield_10042\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10043":"Field \'customfield_10043\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10065":"Field \'customfield_10065\' can       │ not be set. It is not on the appropriate screen, or unknown.","customfield_10044":"Field \'customfield_10044\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10045":"Field \'customfield_10045\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10046":"Field \'customfield_10046\' cannot be set       │ . It is not on the appropriate screen, or unknown.","customfield_10037":"Field \'customfield_10037\' cannot be set. It is not on the appropriate screen, or unknown."}}'

**Comment by SteveMcGrath** [comment]
The `2023-06-26 12:37:32,293 tenable.errors.TioExportsError ERROR vulns export 940848eb-e91a-4cfe-9904-b695ca7e0157 has errored.` Error is from the IO platform itself.  Give it another try, as the export itself had errored.

**Comment by st0ner0ck** [comment]
Thanks Steve but when I did that I ran into the above screen issue.

**Comment by SteveMcGrath** [comment]
You may need to manually set the screens and issuetypes in the config.

https://github.com/tenable/integration-jira-cloud/issues/23#issuecomment-604502293

https://github.com/tenable/integration-jira-cloud/issues/23#issuecomment-604631753

**Comment by st0ner0ck** [comment]
I got it to work Steve. Thanks.
