### ISSUE TITLE
JIRA The Priority Selected Is Invalid

### ISSUE THREAD

**Issue by fabiolanza** [tenable/integration-jira-cloud#234]
Hi,

The script is failing due to prioritization errors. I set the "severity_prioritization" in the config file, in accordance with the priority IDs. However, it seems that the script is still sending requests with the default mapping (1,2,3,4), as can be seen in the log below.

  severity_prioritization:
    critical: 10004
    high: 10000
    low: 10002
    medium: 10001

2023-11-05 08:08:17,356 root DEBUG Severity Prioritization set to: {'critical': 10004, 'high': 10000, 'medium': 10001, 'low': 10002}

2023-11-05 08:08:23,605 tenable_jira.jira.Jira DEBUG Request: {"method": "POST", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/issue", "params": {"update_history": false}, "body": {"fields": {"project": {"key": "VULN"}, "issuetype": {"id": 10017}, "customfield_10424": "-1", "customfield_10425": "10107", "customfield_10426": "Web Servers", "customfield_10427": "HTTP Server Type and Version", **"priority": {"id": "4"}**, "customfield_10428": "Info", "summary": "[10107] HTTP Server Type and Version", "description": {"version": 1, "type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Description"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "This plugin attempts to determine the type and the version of the   remote web server. "}]}, {"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Solution"}]}, {"type": "paragraph", "content": [{"type": "text", "text": " "}]}]}}}}

Can you please help?

Debug follows:

`
### Configuration File:
```yaml
jira:
  address: <REDACTED>
  api_token: <REDACTED>
  api_username: <REDACTED>
project:
  leadAccountId: <REDACTED>
screen:
  jira_ids:
  - 10645
  - 10646
tenable:
  access_key: <REDACTED>
  address: <REDACTED>
  platform: tenable.sc
  query_id: 22697
  secret_key: <REDACTED>
  severity_prioritization:
    critical: 10004
    high: 10000
    low: 10002
    medium: 10001

```

### Debug Logs
```
2023-11-05 08:08:17,354 root INFO Tenable2JiraCloud Version 1.2.3
2023-11-05 08:08:17,354 root INFO Using configuration file config.yaml
2023-11-05 08:08:17,356 root INFO Running on Python3.10.12Linux/x86_64
2023-11-05 08:08:17,356 root DEBUG Severity Prioritization set to: {'critical': 10004, 'high': 10000, 'medium': 10001, 'low': 10002}
2023-11-05 08:08:17,356 tenable.sc.TenableSC DEBUG Request: {"method": "GET", "url": "https://<TENABLE_SC_HOST>:443/rest/system", "params": {}, "body": {}}
2023-11-05 08:08:17,357 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): <TENABLE_SC_HOST>:443
2023-11-05 08:08:17,796 urllib3.connectionpool DEBUG https://<TENABLE_SC_HOST>:443 "GET /rest/system HTTP/1.1" 200 None
2023-11-05 08:08:17,850 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/project/VULN", "params": {}, "body": {}}
2023-11-05 08:08:17,851 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): <JIRA_CLOUD_HOST>:443
2023-11-05 08:08:18,430 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/project/VULN HTTP/1.1" 200 None
2023-11-05 08:08:18,432 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/field", "params": {}, "body": {}}
2023-11-05 08:08:18,782 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/field HTTP/1.1" 200 None
2023-11-05 08:08:18,786 tenable_jira.jira.Jira INFO Tenable Platform is customfield_10418 (existing)
2023-11-05 08:08:18,786 tenable_jira.jira.Jira INFO CVEs is customfield_10419 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO CVSSv2 Base Score is customfield_10420 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO CVSSv2 Temporal Score is customfield_10421 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO CVSSv3 Base Score is customfield_10422 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO CVSSv3 Temporal Score is customfield_10423 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Patch Publication Date is customfield_10424 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Tenable Plugin ID is customfield_10425 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Tenable Plugin Family is customfield_10426 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Tenable Plugin Name is customfield_10427 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Vulnerability Severity is customfield_10428 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Finding Severity is customfield_10429 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Tenable Asset UUID is customfield_10430 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Tenable Asset Tags is customfield_10431 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device MAC Addresses is customfield_10432 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device IPv4 Addresses is customfield_10433 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device IPv6 Addresses is customfield_10434 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device Hostname is customfield_10435 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device NetBIOS Name is customfield_10436 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device DNS Name is customfield_10437 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Device Network ID is customfield_10438 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Vulnerability First Seen is customfield_10439 (existing)
2023-11-05 08:08:18,787 tenable_jira.jira.Jira INFO Vulnerability Last Seen is customfield_10440 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability Last Fixed is customfield_10441 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability State is customfield_10442 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability Port is customfield_10443 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability Protocol is customfield_10444 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability Repository ID is customfield_10445 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Vulnerability Repository Name is customfield_10446 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira INFO Tenable VPR Score is customfield_10447 (existing)
2023-11-05 08:08:18,788 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/project/VULN", "params": {}, "body": {}}
2023-11-05 08:08:19,157 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/project/VULN HTTP/1.1" 200 None
2023-11-05 08:08:19,162 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/issuetype/project", "params": {"projectId": "10410"}, "body": {}}
2023-11-05 08:08:19,282 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/issuetype/project?projectId=10410 HTTP/1.1" 200 None
2023-11-05 08:08:19,284 tenable_jira.transform.Tio2Jira DEBUG Issuetypes standard={'name': 'Task', 'jira_id': 10017, 'type': 'standard', 'search': ['Tenable Plugin ID']}, subtask={'name': 'Sub-task', 'jira_id': 10021, 'type': 'subtask', 'search': ['Tenable Platform', 'Tenable Plugin ID', 'Tenable Asset UUID', 'Device IPv4 Addresses', 'Device IPv6 Addresses', 'Vulnerability Port', 'Vulnerability Protocol']}
2023-11-05 08:08:19,284 tenable_jira.transform.Tio2Jira INFO Using JIRA Screens [10645, 10646]
2023-11-05 08:08:19,284 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10645/tabs", "params": {}, "body": {}}
2023-11-05 08:08:19,526 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10645/tabs HTTP/1.1" 200 None
2023-11-05 08:08:19,528 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10645/tabs/11062/fields", "params": {}, "body": {}}
2023-11-05 08:08:19,708 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10645/tabs/11062/fields HTTP/1.1" 200 None
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO CVEs already exists in 10645:11062
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO Tenable VPR Score already exists in 10645:11062
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO CVSSv2 Base Score already exists in 10645:11062
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO CVSSv2 Temporal Score already exists in 10645:11062
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO CVSSv3 Base Score already exists in 10645:11062
2023-11-05 08:08:19,709 tenable_jira.transform.Tio2Jira INFO CVSSv3 Temporal Score already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Tenable Plugin ID already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Tenable Plugin Family already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Tenable Plugin Name already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability Severity already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability First Seen already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability Last Seen already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability Last Fixed already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability State already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability Port already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Vulnerability Protocol already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Patch Publication Date already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.transform.Tio2Jira INFO Finding Severity already exists in 10645:11062
2023-11-05 08:08:19,710 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10645/tabs/11063/fields", "params": {}, "body": {}}
2023-11-05 08:08:19,902 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10645/tabs/11063/fields HTTP/1.1" 200 None
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Tenable Asset UUID already exists in 10645:11063
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Tenable Asset Tags already exists in 10645:11063
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Tenable Platform already exists in 10645:11063
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Device Hostname already exists in 10645:11063
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Device NetBIOS Name already exists in 10645:11063
2023-11-05 08:08:19,903 tenable_jira.transform.Tio2Jira INFO Device DNS Name already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Device IPv4 Addresses already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Device IPv6 Addresses already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Device MAC Addresses already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Device Network ID already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Vulnerability Repository ID already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.transform.Tio2Jira INFO Vulnerability Repository Name already exists in 10645:11063
2023-11-05 08:08:19,904 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10646/tabs", "params": {}, "body": {}}
2023-11-05 08:08:20,001 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10646/tabs HTTP/1.1" 200 None
2023-11-05 08:08:20,002 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10646/tabs/11064/fields", "params": {}, "body": {}}
2023-11-05 08:08:20,181 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10646/tabs/11064/fields HTTP/1.1" 200 None
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO CVEs already exists in 10646:11064
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO Tenable VPR Score already exists in 10646:11064
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO CVSSv2 Base Score already exists in 10646:11064
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO CVSSv2 Temporal Score already exists in 10646:11064
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO CVSSv3 Base Score already exists in 10646:11064
2023-11-05 08:08:20,184 tenable_jira.transform.Tio2Jira INFO CVSSv3 Temporal Score already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Tenable Plugin ID already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Tenable Plugin Family already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Tenable Plugin Name already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability Severity already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability First Seen already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability Last Seen already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability Last Fixed already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability State already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability Port already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Vulnerability Protocol already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Patch Publication Date already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.transform.Tio2Jira INFO Finding Severity already exists in 10646:11064
2023-11-05 08:08:20,185 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/screens/10646/tabs/11065/fields", "params": {}, "body": {}}
2023-11-05 08:08:20,411 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "GET /rest/api/3/screens/10646/tabs/11065/fields HTTP/1.1" 200 None
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Tenable Asset UUID already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Tenable Asset Tags already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Tenable Platform already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device Hostname already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device NetBIOS Name already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device DNS Name already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device IPv4 Addresses already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device IPv6 Addresses already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device MAC Addresses already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Device Network ID already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Vulnerability Repository ID already exists in 10646:11065
2023-11-05 08:08:20,414 tenable_jira.transform.Tio2Jira INFO Vulnerability Repository Name already exists in 10646:11065
2023-11-05 08:08:20,414 tenable.sc.TenableSC DEBUG Request: {"method": "GET", "url": "https://<TENABLE_SC_HOST>:443/rest/query/22697?fields=filters", "params": {}, "body": {}}
2023-11-05 08:08:20,576 urllib3.connectionpool DEBUG https://<TENABLE_SC_HOST>:443 "GET /rest/query/22697?fields=filters HTTP/1.1" 200 125
2023-11-05 08:08:20,577 tenable.sc.TenableSC DEBUG Request: {"method": "POST", "url": "https://<TENABLE_SC_HOST>:443/rest/analysis", "params": {}, "body": {"type": "vuln", "sourceType": "cumulative", "query": {"tool": "vulndetails", "type": "vuln", "filters": [{"filterName": "lastSeen", "operator": "=", "value": "0-1699168100"}], "startOffset": 0, "endOffset": 1000}}}
2023-11-05 08:08:21,742 urllib3.connectionpool DEBUG https://<TENABLE_SC_HOST>:443 "POST /rest/analysis HTTP/1.1" 200 None
2023-11-05 08:08:23,241 tenable_jira.transform.Tio2Jira DEBUG Setting Vuln Sev to info
2023-11-05 08:08:23,241 tenable_jira.transform.Tio2Jira DEBUG Setting Finding Sev to info
2023-11-05 08:08:23,245 tenable_jira.jira.Jira DEBUG Request: {"method": "POST", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/search", "params": {}, "body": {"jql": "project = \"VULN\" and issuetype = \"Task\" and status not in (Closed, Done, Resolved) and \"Tenable Plugin ID\" ~ \"10107\""}}
2023-11-05 08:08:23,603 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "POST /rest/api/3/search HTTP/1.1" 200 None
2023-11-05 08:08:23,605 tenable_jira.jira.Jira DEBUG Request: {"method": "POST", "url": "https://<JIRA_CLOUD_HOST>/rest/api/3/issue", "params": {"update_history": false}, "body": {"fields": {"project": {"key": "VULN"}, "issuetype": {"id": 10017}, "customfield_10424": "-1", "customfield_10425": "10107", "customfield_10426": "Web Servers", "customfield_10427": "HTTP Server Type and Version", "priority": {"id": "4"}, "customfield_10428": "Info", "summary": "[10107] HTTP Server Type and Version", "description": {"version": 1, "type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Description"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "This plugin attempts to determine the type and the version of the   remote web server. "}]}, {"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Solution"}]}, {"type": "paragraph", "content": [{"type": "text", "text": " "}]}]}}}}
2023-11-05 08:08:23,982 urllib3.connectionpool DEBUG https://<JIRA_CLOUD_HOST>:443 "POST /rest/api/3/issue?update_history=False HTTP/1.1" 400 None
2023-11-05 08:08:23,983 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'
2023-11-05 08:08:23,984 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/transform.py", line 409, in _process_open_vuln
    i = self._jira.issues.upsert(fields=issue, jql=' and '.join(jql))
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/jira/issues.py", line 48, in upsert
    issue = self.create(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/jira/issues.py", line 18, in create
    return self._api.post('issue',
  File "/usr/local/lib/python3.10/dist-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/cli.py", line 156, in cli
    ingest.ingest(int(observed_since), first_discovery)
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/transform.py", line 736, in ingest
    self.create_issues(vulns)
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/transform.py", line 529, in create_issues
    self._process_open_vuln(v, fid)
  File "/usr/local/lib/python3.10/dist-packages/tenable_jira/transform.py", line 412, in _process_open_vuln
    sys.exit(2)
SystemExit: 2

```

### Available IssueTypes
```yaml
10110: Subtask
10021: Sub-task
10112: Sub-task
10105: Subtask
10121: Subtask
10117: Sub-task
10115: Sub-task
10063: Task
10107: Task
10102: Task
10017: Task
10114: Task
10116: Task
10119: Task
10111: Task
```
`

**Comment by SteveMcGrath** [comment]
https://github.com/tenable/integration-jira-cloud/issues/233#issuecomment-1802279827

**Comment by fabiolanza** [comment]
> [#233 (comment)](https://github.com/tenable/integration-jira-cloud/issues/233#issuecomment-1802279827)

Thanks, I understand that there is a Info severity that has not a mapping in Jira, which is causing the issue. I would not create tickets for Info severity. Is it possible to instruct the script to ignore findings with Info severity? How to do that?

Thank you

**Comment by fabiolanza** [comment]
I changed the query in Tenable SC to filter out Info severity and now it's working.
