### ISSUE TITLE
Frozen RUNPY error - Python 3.12.1

### ISSUE THREAD

**Issue by PaulW8080** [tenable/integration-jira-cloud#242]
Hi, I need some help here, new to python and i am getting the below errors. I am unsure how to troubleshoot this and have searched some forums with little help. Is there a compatibility issue with this version of python and the code? 

(JIRA) \AppData\Local\Programs\Python\Python312\JIRA\Scripts>tenable-jira config.yaml
Traceback (most recent call last):
  File "frozen runpy", line 198, in _run_module_as_main
  File "frozen runpy", line 88, in _run_code
  File "\AppData\Local\Programs\Python\Python312\JIRA\Scripts\tenable-jira.exe\__main__.py", line 4, in module
  File "\AppData\Local\Programs\Python\Python312\JIRA\Lib\site-packages\tenable_jira\cli.py", line 31, in module
    from .transform import Tio2Jira
  File "\AppData\Local\Programs\Python\Python312\JIRA\Lib\site-packages\tenable_jira\transform.py", line 3, in module
    from pkg_resources import resource_string as embedded
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by normlee-fbg** [comment]
@PaulW8080 I encountered the same error with Python 3.12.  I went back and used Python 3.7.9 and it worked.

**Comment by PaulW8080** [comment]
Thanks @normlee-fbg for the feedback. The only issue I have with python 3.7.9 is that it is no longer supported for updates and vulnerabilities so I can't use it for my company. Does anyone have the ability to run this with version 3.12 or a newer version that is supported?

**Comment by SteveMcGrath** [comment]
Working on a new version that no longer has these requirements.

**Comment by SteveMcGrath** [comment]
The rewrite of the integration has been released and should no longer have any issues with 3.12
