### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Kerb1ah** [tenable/integration-jira-cloud#29]
Hi Steven,

When I try to run the connector I get a TypeError.

`File "/opt/anaconda3/lib/python3.7/site-packages/tenable_jira/jira/screens.py", line 11, in _get_page
    self.total = resp['total']
TypeError: list indices must be integers or slices, not str`

If I `print(resp)` it appears to give me a JSON of all the screens available in my Jira instance. I am not really sure what I should be looking at to try and troubleshoot.

Thanks,
Peter

**Comment by SteveMcGrath** [comment]
can you please provide the debug logging and a sanitized config file?

**Comment by Kerb1ah** [comment]
Here's the traceback and debug:

`Tenable-Jira user$ tenable-jira config.yaml
2020-04-08 08:34:24,154 root INFO Tenable2JiraCloud Version 1.1.3
2020-04-08 08:34:24,154 root INFO Using configuration file config.yaml
2020-04-08 08:34:24,169 root INFO Running on Python 3.7.4 Darwin/x86_64
2020-04-08 08:34:24,217 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): atlassian.com: 
2020-04-08 08:34:24,766 urllib3.connectionpool DEBUG atlassian.com  "GET /rest/api/latest/project/VMNGT HTTP/1.1" 200 None
2020-04-08 08:34:24,994 urllib3.connectionpool DEBUG atlassian.com  "GET /rest/api/latest/field HTTP/1.1" 200 None
2020-04-08 08:34:25,142 urllib3.connectionpool DEBUG atlassian.com  "GET /rest/api/latest/issuetype HTTP/1.1" 200 None
2020-04-08 08:34:25,144 tenable_jira.jira.Jira DEBUG uri=atlassian/rest/api/latest/screens, query={'startAt': 0, 'maxResults': 100}, body={}
2020-04-08 08:34:25,372 urllib3.connectionpool DEBUG https://atlassian.com "GET /rest/api/latest/screens?startAt=0&maxResults=100 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tenable_jira/cli.py", line 100, in cli
    ingest = Tio2Jira(source, jira, config)
  File "/opt/anaconda3/lib/python3.7/site-packages/tenable_jira/transform.py", line 23, in __init__
    self.screen_builder()
  File "/opt/anaconda3/lib/python3.7/site-packages/tenable_jira/transform.py", line 46, in screen_builder
    for item in self._jira.screens.list():
  File "/opt/anaconda3/lib/python3.7/site-packages/restfly/iterator.py", line 107, in __next__
    return self.next()
  File "/opt/anaconda3/lib/python3.7/site-packages/restfly/iterator.py", line 134, in next
    self._get_page()
  File "/opt/anaconda3/lib/python3.7/site-packages/tenable_jira/jira/screens.py", line 11, in _get_page
    self.total = resp['total']
TypeError: list indices must be integers or slices, not str`

Here is config.yaml:

`tenable:
  # Tenable.io or API Access Key
  access_key: removed

  # Tenable.io or API Secret Key
  secret_key: removed

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: removed

  # The User that will be authenticating to the Jira application
  api_username: removed

  # The address pointing to the Jira application.
  address: removed

project:
  key: VMNGT
  name: Tenable Vulnerability Management

  # The lead account id for the primary user for the project.
  lead: me

  #The name of the Jira Project
  #name: Vulnerability Management

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: debug`

I let the connector set up the project.

**Comment by SteveMcGrath** [comment]
Well thats a new one.  Jira's is violating its API contract if thats the case.

I'm assuming that you had scrubbed the subdomain from the logs?  It really wasn't `https://atlassian.com`, right?

**Comment by Kerb1ah** [comment]
That's right it points to an AWS instance. Apologies, I didn't think about it when I put that in. Will use example.com in future.

**Comment by Kerb1ah** [comment]
The Jira dev had a look at this for me and he has fixed it. He is going to give me a brief summary of what he's done. I will update here for visibility.
