### ISSUE TITLE
 Failed to establish a new connection when ran tenable-jira config.yaml comand

### ISSUE THREAD

**Issue by wishhard** [tenable/integration-jira-cloud#68]
i ran tenable-jira config.yaml and it gave me the following error
```
2020-09-07 21:34:39,833 tenable_jira.jira.Jira ERROR Requests Library Error: HTTPSConnectionPool(host='https;', port=443): Max retries exceeded with url: //potomaceconomics.atlassian.net/rest/api/3/project/VULN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f081402f9e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2020-09-07 21:34:40,841 tenable_jira.jira.Jira ERROR Requests Library Error: HTTPSConnectionPool(host='https;', port=443): Max retries exceeded with url: //potomaceconomics.atlassian.net/rest/api/3/project/VULN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f081402f9e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2020-09-07 21:34:41,849 tenable_jira.jira.Jira ERROR Requests Library Error: HTTPSConnectionPool(host='https;', port=443): Max retries exceeded with url: //potomaceconomics.atlassian.net/rest/api/3/project/VULN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f081402fd68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2020-09-07 21:34:42,855 tenable_jira.jira.Jira ERROR Requests Library Error: HTTPSConnectionPool(host='https;', port=443): Max retries exceeded with url: //potomaceconomics.atlassian.net/rest/api/3/project/VULN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f081402e940>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Traceback (most recent call last):
  File "/home/waqas/anaconda3/envs/ten_fr_jc/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/tenable_jira/cli.py", line 126, in cli
    ingest = Tio2Jira(source, jira, config)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/tenable_jira/transform.py", line 24, in __init__
    self._project = self._jira.projects.upsert(**config['project'])
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/tenable_jira/jira/projects.py", line 32, in upsert
    return self.details(kwargs['key'])
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/tenable_jira/jira/projects.py", line 9, in details
    return self._api.get('project/{}'.format(id), params=kwargs).json()
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/restfly/session.py", line 538, in get
    return self._request('GET', path, **kwargs)
  File "/home/waqas/anaconda3/envs/ten_fr_jc/lib/python3.6/site-packages/restfly/session.py", line 513, in _request
    raise err(resp, retries=retries, func=self._error_func)
UnboundLocalError: local variable 'err' referenced before assignment`
```
I use anaconda python envs both in windows and linux. Both produced the sane error.
On win i used python 3.7 evn and on linux python 3.6 and 3.7.

**Comment by SteveMcGrath** [comment]
Looks like its having an issue communicating to `potomaceconomics.atlassian.net`

**Comment by SteveMcGrath** [comment]
Closing due to lack of response
