### ISSUE TITLE
yaml CLoader error when running integration command

### ISSUE THREAD

**Issue by cthulnado** [tenable/integration-jira-cloud#7]
pip Installed PyYAML, pip installed integration. Created config.yaml. Ran the tenable-jira config.yaml command and get the error below. Others are getting the same error.

`➜  ~ tenable-jira config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenable_jira/cli.py", line 42, in cli
    base_config(),
  File "/usr/local/lib/python3.7/site-packages/tenable_jira/config.py", line 4, in base_config
    return yaml.load(config, Loader=yaml.CLoader)
AttributeError: module 'yaml' has no attribute 'CLoader'`

**Comment by SteveMcGrath** [comment]
Remediated in:

ad4ab49ab28bb805986af803e84c34cb05f3b7f5
c3fb7fc6e85497d3e5338b453967397e84c24eca
