### ISSUE TITLE
AWS Info and v1.1.14

### ISSUE THREAD

**Issue by evazquez00** [tenable/integration-jira-cloud#70]
New issue:

When the `tio_field` variable is changed to use AWS information (`[{vuln[asset.aws_ec2_instance_group_name]}/{vuln[asset.aws_ec2_name]}`), new devices that are not AWS related, such as Remote Agents or local office systems show up as "None/None", as in:

`[None/None/445/TCP] [138522] Oracle Java SE 1.7.0_271 / 1.8.0_261 / 1.11.0_8 / 1.14.0_2 Multiple Vulnerabilities (Jul 2020 CPU)`

Is there a way to fall-back to DNS name if AWS does not exist (e.g. for Remote Agents)?

**Comment by evazquez00** [comment]
I did try poking at the Python, but I'm not familiar enough with YAML to get it right...

Here's what I tried:

```issue_default_fields:
  summary:
    Sub-task:
      if {vuln[asset.aws_ec2_name]} = null:
        tio_field: '[{vuln[asset.hostname]}/{vuln[port.port]}/{vuln[port.protocol]}] [{vuln[plugin.id]}] {vuln[plugin.name]}'
      else:
        tio_field: '[{vuln[asset.aws_ec2_instance_group_name]}/{vuln[asset.aws_ec2_name]}/{vuln[port.port]}/{vuln[port.protocol]}] [{vuln[plugin.id]}] {vuln[plugin.name]}'```

It still sets Sub-Task CREATE and UPDATE with None/None for non-AWS assets.

**Comment by SteveMcGrath** [comment]
try:

```yaml
issue_default_fields:
  summary:
    Sub-task:
      tio_field: '[{vuln.get('asset.aws_ec2_instance_group_name')}/{vuln.get('asset.aws_ec2_name','asset.hostname')}/{vuln[port.port]}/{vuln[port.protocol]/[vuln[plugin.id]}] {vuln[plugin.name]}'
```

**Comment by evazquez00** [comment]
Hmm, I get:

Traceback (most recent call last):
  File "/home/evazquez/.local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/cli.py", line 187, in cli
    ingest.ingest(observed_since)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 597, in ingest
    self.create_issues(vulns)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 476, in create_issues
    self._process_open_vuln(v, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 359, in _process_open_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 318, in _process_vuln
    subissue[field] = self._gen_doc_format(
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 211, in _gen_doc_format
    return fdef[fid].format(vuln=vuln)
AttributeError: 'dict' object has no attribute 'get("asset'

**Comment by evazquez00** [comment]
I fiddled around a bit and have it somewhat working...

If I use:

`tio_field: '[{vuln[asset.aws_ec2_instance_group_name]}/{vuln[asset.aws_ec2_name]},{vuln[asset.hostname]}/{vuln[port.port]}/{vuln[port.protocol]}] [{vuln[plugin.id]}] {vuln[plugin.name]}'`

it pulls the data correctly and updates with AWS Group and Name.

For clean presentation, it would be great if the "None/None" could be dropped if it doesn't exist, but I'll take this as a workable result.

**Comment by evazquez00** [comment]
New issue now that the AWS data is available...

With the above configuration for `tio_field`, the script runs for a bit, then throws:

```$ tenable-jira -s $(date -d '-3 day' +%s) ./SageSure/jira-test.yaml 
Traceback (most recent call last):
  File "/home/evazquez/.local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/cli.py", line 187, in cli
    ingest.ingest(observed_since)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 607, in ingest
    self.close_issues(closed)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 508, in close_issues
    self._process_closed_vuln(v, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 402, in _process_closed_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 318, in _process_vuln
    subissue[field] = self._gen_doc_format(
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 211, in _gen_doc_format
    return fdef[fid].format(vuln=vuln)
KeyError: 'asset.aws_ec2_instance_group_name'
```

**Comment by SteveMcGrath** [comment]
is `aws_ec2_instance_group_name` in the asset attribute cache like so?

```yaml
tenable:
  tio_asset_attr_cache:
  - aws_availability_zone
  - aws_ec2_instance_ami_id
  - aws_ec2_instance_group_name
  - aws_ec2_instance_id
  - aws_ec2_instance_state_name
  - aws_ec2_instance_type
  - aws_ec2_name
  - aws_ec2_product_code
  - aws_owner_id
  - aws_region
  - aws_subnet_id
  - aws_vpc_id
```

Also note that the field listing is in the response of this call:

https://developer.tenable.com/reference#exports-assets-download-chunk

**Comment by evazquez00** [comment]
Here's what I have in my YAML:

The weird thing is that it works and shows as updating /creating JIRA tickets with the AWS info until it reaches a random record (three runs, same error, different record /place each time) and bails.

'''tenable:
  tio_asset_attr_cache:
    - aws_ec2_instance_group_name
    - aws_ec2_name
```

and the other section is:

```screen:
  jira_ids: 
    - 16783
    - 16784
  tabs:
    Asset:
    - Tenable Asset UUID
    - Tenable Asset Tags
    - Tenable Platform
    - AWS Instance Group Name
    - AWS Name
    - Device Hostname
    - Device NetBIOS Name
    - Device DNS Name
    - Device IPv4 Addresses
    - Device IPv6 Addresses
    - Device MAC Addresses
    - Device Network ID
    - Vulnerability Repository ID
    - Vulnerability Repository Name
    - AWS Instance ID

    - jira_field: AWS Instance Group Name
      type: labels
      searcher: labelsearcher
      issue_type:
      - Sub-Task
      tio_field: asset.aws_ec2_instance_group_name
```

**Comment by evazquez00** [comment]
I've been running the script, with and without debug turned on in the YAML.

When it runs with "log: level: info" it throws the error above in the log file.

When it runs with "log: level: debug" no error is seen.

`--troubleshoot` on the command line does not make any difference in error generation.

Most puzzling...

**Comment by evazquez00** [comment]
pyTenable updated to v1.2.2 and now I finally caught the error during a "debug" log session.

What I see on the command line is:
```$ tenable-jira -s $(date -d '-1 day' +%s) ./SageSure/jira-test.yaml 
Traceback (most recent call last):
  File "/home/evazquez/.local/bin/tenable-jira", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/cli.py", line 187, in cli
    ingest.ingest(observed_since)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 597, in ingest
    self.create_issues(vulns)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 476, in create_issues
    self._process_open_vuln(v, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 359, in _process_open_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 318, in _process_vuln
    subissue[field] = self._gen_doc_format(
  File "/home/evazquez/.local/lib/python3.8/site-packages/tenable_jira/transform.py", line 211, in _gen_doc_format
    return fdef[fid].format(vuln=vuln)
KeyError: 'asset.aws_ec2_instance_group_name'
```   

and in the debug log:
```2020-09-22 07:54:31,779 tenable.io.TenableIO DEBUG {"method": "POST", "url": "https://cloud.tenable.com/vulns/export", "params": {}, "body": {"filters": {"last_found": 1600696457, "severity": ["critical", "high", "medium"]}, "num_assets": "1000"}}
2020-09-22 07:54:32,718 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 200 None
2020-09-22 07:54:32,718 tenable.io.TenableIO DEBUG Request-UUID 7ca66ce317a893404e43be06b7ae59d0 for https://cloud.tenable.com/vulns/export
2020-09-22 07:54:32,718 tenable.io.TenableIO DEBUG Initiated vuln export 3cf4e3e5-8413-4959-8e48-1dad00c0d3ab
2020-09-22 07:54:32,718 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status", "params": {}, "body": {}}
2020-09-22 07:54:33,904 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status HTTP/1.1" 200 None
2020-09-22 07:54:33,905 tenable.io.TenableIO DEBUG Request-UUID 3ec39a365f84df4d85eb4427ad163b0d for https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status
2020-09-22 07:54:35,908 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status", "params": {}, "body": {}}
2020-09-22 07:54:36,012 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status HTTP/1.1" 200 None
2020-09-22 07:54:36,013 tenable.io.TenableIO DEBUG Request-UUID 5c64c85e03d46b1cbfa0b469443dabc1 for https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status
2020-09-22 07:54:39,019 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status", "params": {}, "body": {}}
2020-09-22 07:54:39,129 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status HTTP/1.1" 200 None
2020-09-22 07:54:39,133 tenable.io.TenableIO DEBUG Request-UUID 346f2193ade91be5365b367f7a4194af for https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status
2020-09-22 07:54:43,138 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status", "params": {}, "body": {}}
2020-09-22 07:54:43,240 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status HTTP/1.1" 200 None
2020-09-22 07:54:43,241 tenable.io.TenableIO DEBUG Request-UUID bc5c980bfebfd265198c6c6357c9b8b0 for https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/status
2020-09-22 07:54:43,241 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/chunks/1", "params": {}, "body": {}}
2020-09-22 07:54:44,534 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/chunks/1 HTTP/1.1" 200 149967
2020-09-22 07:54:44,618 tenable.io.TenableIO DEBUG Request-UUID 9bba61bfaac7f0439a7124764b0d962b for https://cloud.tenable.com/vulns/export/3cf4e3e5-8413-4959-8e48-1dad00c0d3ab/chunks/1
```

Full "issue_debug_md.txt" log file attached for your morning eye-strain...
[issue_debug_md.txt](https://github.com/tenable/integration-jira-cloud/files/5261960/issue_debug_md.txt)

**Comment by SteveMcGrath** [comment]
Alrighty, I think this issue and #75 are related due to some of the changes you made to the config.  As noted in https://github.com/tenable/integration-jira-cloud/issues/69#issuecomment-691196283 you need to add the fields to the right stanza.  Here is a completed example using the custom_fields stanza added for 1.1.15.  Prior to that as noted in the linked comment, you would have had to copy all of the fields already configured and then add yours at the end.  for 1.1.15, the following is possible:

```yaml
screen:
  tabs:
    Asset:
    - Tenable Asset UUID
    - Tenable Asset Tags
    - Tenable Platform
    - AWS Instance Group Name
    - AWS Name
    - Device Hostname
    - Device NetBIOS Name
    - Device DNS Name
    - Device IPv4 Addresses
    - Device IPv6 Addresses
    - Device MAC Addresses
    - Device Network ID
    - Vulnerability Repository ID
    - Vulnerability Repository Name
    - AWS Instance ID
    - AWS Name

tenable:
  platform: tenable.io
  access_key: XXXX
  secret_key: XXXX
  tio_tags:
    - key: Device-Type
      value: Agented
  tio_severities:
  - medium
  - high
  - critical
  tio_asset_attr_cache:
  - agent_uuid
  - bios_uuid
  - aws_ec2_instance_group_name
  - aws_ec2_name
  severity_prioritization:
    critical: 1
    high: 2
    medium: 3
    low: 4

jira:
  api_token: XXXX
  api_username: XXXX
  address: XXXX

project:
  key: VULN2
  name: Vuln Management Test2
  leadAccountId: XXXX

issue_default_fields:
  summary:
    Sub-task:
      tio_field: 'ec2[{vuln[asset.aws_ec2_instance_group_name]}/{vuln[asset.aws_ec2_name]}] [{vuln[asset.hostname]}/{vuln[port.port]}/{vuln[port.protocol]}/{vuln[plugin.id]}] {vuln[plugin.name]}'

custom_fields:
  - issue_type:
    - Sub-Task
    jira_field: AWS Instance Group Name
    searcher: labelsearcher
    tio_field: asset.aws_ec2_instance_group_name
    type: labels
  - issue_type:
    - Sub-Task
    jira_field: AWS Name
    searcher: labelsearcher
    tio_field: asset.aws_ec2_name
    type: labels
```

**Comment by evazquez00** [comment]
Ah, so it's really:
`custom_fields`
and not
`fields` as it seemed to be here:
https://github.com/tenable/integration-jira-cloud/blob/d45d86dc56f5ed4ca48bfbe6f77e58ee39630312/tenable_jira/config.py#L217-L220

Once I added `custom_` to the name of the stanza, it seems to be working.

Thank you!

**Comment by evazquez00** [comment]
With the stanza change to `custom_fields`, it all seems to be working.

Thank you!
