### ISSUE TITLE
ImportError: cannot import name 'AnalysisAPI'

### ISSUE THREAD

**Issue by branfarm** [tenable/integration-jira-cloud#86]
Trying to run the integration to link Tenable.io to Jira cloud but receiving this error: 

(jira) [root@util01 jira]# tenable-jira /root/tenable.yaml
Traceback (most recent call last):
  File "/root/jira/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.17', 'console_scripts', 'tenable-jira')()
  File "/root/jira/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/jira/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/root/jira/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/root/jira/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/jira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 27, in <module>
    from tenable.sc import TenableSC
  File "/root/jira/lib64/python3.6/site-packages/tenable/sc/__init__.py", line 73, in <module>
    from .analysis import AnalysisAPI
ImportError: cannot import name 'AnalysisAPI'

Happens even when I run tenable-jira with no options.  Tried removing the venv and starting again but hitting the same thing.   Any ideas what I'm missing?

**Comment by patrickoneiltc** [comment]
Same error here. The Analysis API __init__.py and api.py are blank files.

**Comment by SteveMcGrath** [comment]
This was an issue related to a dirty build environment.  1.2.4 was removed and 1.2.5 uploaded to replace it.  please update.

**Comment by branfarm** [comment]
That did it -- thank you!
