### ISSUE TITLE
Script error with issues

### ISSUE THREAD

**Issue by feisa** [tenable/integration-jira-cloud#89]
We are trying to run the plugin setup and receive the following

tenable-jira config.yaml 
2020-12-16 02:17:34,139 root INFO Tenable2JiraCloud Version 1.1.17
2020-12-16 02:17:34,139 root INFO Using configuration file config.yaml
2020-12-16 02:17:34,139 root INFO Running on Python 3.6.8 Linux/x86_64
2020-12-16 02:17:34,140 tenable.io.TenableIO DEBUG {"method": "GET", "url": "https://cloud.tenable.com/session", "params": {}, "body": {}}
2020-12-16 02:17:34,142 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): cloud.tenable.com:443
2020-12-16 02:17:34,468 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /session HTTP/1.1" 200 None
2020-12-16 02:17:34,469 tenable.io.TenableIO DEBUG Request-UUID 8f67a8fcdf77744b3d7533fa8dab0eae for https://cloud.tenable.com/session
2020-12-16 02:17:34,469 tenable_jira.jira.Jira DEBUG Request:{"method": "GET", "url": "https://testorg.atlassian.net/rest/api/3/project/VULN", "params": {}, "body": {}}
2020-12-16 02:17:34,470 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): testorg.atlassian.net:443
2020-12-16 02:17:34,660 urllib3.connectionpool DEBUG https://testorg.atlassian.net:443 "GET /rest/api/3/project/VULN HTTP/1.1" 200 None
2020-12-16 02:17:34,662 tenable_jira.jira.Jira DEBUG Request:{"method": "GET", "url": "https://testorg.atlassian.net/rest/api/3/field", "params": {}, "body": {}}
2020-12-16 02:17:34,844 urllib3.connectionpool DEBUG https://testorg.atlassian.net:443 "GET /rest/api/3/field HTTP/1.1" 200 None
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Platform is customfield_10943 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO CVEs is customfield_10944 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO CVSSv2 Base Score is customfield_10945 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO CVSSv2 Temporal Score is customfield_10946 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO CVSSv3 Base Score is customfield_10947 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO CVSSv3 Temporal Score is customfield_10948 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Patch Publication Date is customfield_10949 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Plugin ID is customfield_10950 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Plugin Family is customfield_10951 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Plugin Name is customfield_10952 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Vulnerability Severity is customfield_10953 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Asset UUID is customfield_10954 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Tenable Asset Tags is customfield_10955 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device MAC Addresses is customfield_10956 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device IPv4 Addresses is customfield_10957 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device IPv6 Addresses is customfield_10958 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device Hostname is customfield_10959 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device NetBIOS Name is customfield_10960 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device DNS Name is customfield_10961 (existing)
2020-12-16 02:17:34,886 tenable_jira.jira.Jira INFO Device Network ID is customfield_10962 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability First Seen is customfield_10963 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Last Seen is customfield_10964 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Last Fixed is customfield_10965 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability State is customfield_10966 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Port is customfield_10967 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Protocol is customfield_10968 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Repository ID is customfield_10969 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Vulnerability Repository Name is customfield_10970 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira INFO Tenable VPR Score is customfield_10971 (existing)
2020-12-16 02:17:34,887 tenable_jira.jira.Jira DEBUG Request:{"method": "GET", "url": "https://testorg.atlassian.net/rest/api/3/issuetype", "params": {}, "body": {}}
2020-12-16 02:17:34,972 urllib3.connectionpool DEBUG https://testorg.atlassian.net:443 "GET /rest/api/3/issuetype HTTP/1.1" 200 None
2020-12-16 02:17:34,974 tenable_jira.jira.Jira DEBUG Request:{"method": "POST", "url": "https://testorg.atlassian.net/rest/api/3/issuetype", "params": {}, "body": {"name": "Sub-task", "description": "", "type": "subtask"}}
2020-12-16 02:17:35,048 urllib3.connectionpool DEBUG https://testorg.atlassian.net:443 "POST /rest/api/3/issuetype HTTP/1.1" 409 None
2020-12-16 02:17:35,053 restfly.errors.RequestConflictError ERROR [409: POST] https://testorg.atlassian.net/rest/api/3/issuetype body=b'{"errorMessages":[],"errors":{"name":"An issue type with this name already exists."}}'
Traceback (most recent call last):
  File "/usr/local/bin/tenable-jira", line 33, in <module>
    sys.exit(load_entry_point('tenable-jira-cloud==1.1.17', 'console_scripts', 'tenable-jira')())
  File "/home/feisa/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/feisa/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/feisa/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/feisa/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/cli.py", line 143, in cli
    ingest = Tio2Jira(source, jira, config)
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/transform.py", line 26, in __init__
    self._issue_types = self._jira.issue_types.upsert(config['issue_types'])
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/jira/issuetypes.py", line 29, in upsert
    type=issuetype['type']
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/jira/issuetypes.py", line 11, in create
    return self._api.post('issuetype', json=kwargs).json()
  File "/home/feisa/.local/lib/python3.6/site-packages/restfly/session.py", line 563, in post
    return self._request('POST', path, **kwargs)
  File "/home/feisa/.local/lib/python3.6/site-packages/restfly/session.py", line 477, in _request
    raise err(resp, retries=retries, func=self._error_func)
restfly.errors.RequestConflictError: [409: POST] https://testorg.atlassian.net/rest/api/3/issuetype body=b'{"errorMessages":[],"errors":{"name":"An issue type with this name already exists."}}

**Comment by SteveMcGrath** [comment]
Please note: https://github.com/tenable/integration-jira-cloud#common-problems

**Comment by feisa** [comment]
Little closer 

2020-12-16 11:21:40,050 restfly.errors.BadRequestError ERROR [400: POST] https://crabel.atlassian.net/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_10951":"Field \'customfield_10951\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10952":"Field \'customfield_10952\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10953":"Field \'customfield_10953\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10944":"Field \'customfield_10944\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10945":"Field \'customfield_10945\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10946":"Field \'customfield_10946\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10947":"Field \'customfield_10947\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10948":"Field \'customfield_10948\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10949":"Field \'customfield_10949\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10971":"Field \'customfield_10971\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10950":"Field \'customfield_10950\' cannot be set. It is not on the appropriate screen, or unknown."}}'

**Comment by feisa** [comment]
From the troubleshooting file   

 raise err(resp, retries=retries, func=self._error_func)
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"customfield_10951":"Field \'customfield_10951\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10952":"Field \'customfield_10952\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10953":"Field \'customfield_10953\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10944":"Field \'customfield_10944\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10945":"Field \'customfield_10945\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10946":"Field \'customfield_10946\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10947":"Field \'customfield_10947\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10948":"Field \'customfield_10948\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10949":"Field \'customfield_10949\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10971":"Field \'customfield_10971\' cannot be set. It is not on the appropriate screen, or unknown.","customfield_10950":"Field \'customfield_10950\' cannot be set. It is not on the appropriate screen, or unknown."}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/cli.py", line 151, in cli
    ingest.ingest(observed_since)
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/transform.py", line 608, in ingest
    self.create_issues(vulns)
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/transform.py", line 477, in create_issues
    self._process_open_vuln(v, fid)
  File "/home/feisa/.local/lib/python3.6/site-packages/tenable_jira/transform.py", line 366, in _process_open_vuln
    sys.exit(2)
SystemExit: 2

```

### Available IssueTypes
```yaml
10603: Sub-Task
3: Task
10772: Task
10704: Task
10702: Task
10740: Task
10708: Task
10838: Subtask
10836: Task
10742: Subtask
10746: Subtask
10755: Task
10758: Subtask
10761: Subtask
10759: Task
10774: Subtask
10775: Task
10777: Subtask
10778: Task
10780: Subtask
```

**Comment by feisa** [comment]
I added this based on the post,  

issue_types:
  - jira_id: 3
    name: Task
    type: standard
    search:
    - Tenable Plugin ID
  - jira_id: 10000
    name: Sub-task
    type: subtask
    search:
    - Tenable Plugin ID
    - Tenable Asset UUID
    - Device IPv4
    - Device IPv6
    - Vulnerability Port
    - Vulnerability Protocol

~

**Comment by feisa** [comment]
Thanks again I appreciate the help. I would like to get this working

**Comment by SteveMcGrath** [comment]
The troubleshooting output leads me to believe you'll need to manually specify the screen IDs.  This is typically the case if the screen names are duplicated.  Again, note the link under common issues related to that.

**Comment by feisa** [comment]
@SteveMcGrath im sorry i dont understand. Can you walk me through this?

**Comment by SteveMcGrath** [comment]
As mentioned above, its detailed under common issues in the readme, please refer to https://github.com/tenable/integration-jira-cloud/issues/23#issuecomment-604631753

**Comment by feisa** [comment]
thanks this is resolved,

**Comment by feisa** [comment]
i hate jira, thanks
