### ISSUE TITLE
TIO/TSC integration with Jira Cloud not working

### ISSUE THREAD

**Issue by bn-stephen** [tenable/integration-jira-cloud#92]
Greetings,

I am trying out to integrate both TIO and TSC with Jira Cloud (Jira Software), but there were some error encountered (_Field \'customfield_10038\' cannot be set. It is not on the appropriate screen, or unknown._) while using the plugin.

Tenbable.io Version: N/A
Tenable.sc Version: 5.15.0
Jira Cloud Version: N/A
Tenable for Jira Cloud Plugin Version: 1.1.18

I had also tried deleting the automatically created VULN project and redo the steps, but the same error occurs.
Please find the troubleshooting log generated from both TIO and TSC config file for your assistance.

[debug_log.zip](https://github.com/tenable/integration-jira-cloud/files/5812756/debug_log.zip)

**Comment by SteveMcGrath** [comment]
Looks like the screens that have been selected were 10003 and 10004.  Can you please verify that those screen ids are correct?  If you had deleted the project and did not clean up the old screens, it's likely still selecting the older screen ids.

It also looks like you only have 10002 for task and 10003 for Sub-Task, however it can't hurt to verify.  The information your looking for is under the "Common Problems" section of the readme.

**Comment by bn-stephen** [comment]
Dear Steve,

Thanks for your prompt response and recommendation.

I had started fresh again; deleting the project and all the fields/screens, then followed by running
```
tenable-jira config.yaml --setup-only
tenable-jira generated_config.yaml
```

Unfortunately, the following error occurs.

```
2021-01-15 13:08:46,347 restfly.errors.BadRequestError ERROR [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":["We can\'t create this issue for you right now, it could be due to unsupported content you\'ve entered into one or more of the issue fields. If this situation persists, contact your administrator as they\'ll be able to access more specific information in the log file."],"errors":{}}'
2021-01-15 13:08:46,347 root ERROR Caught the following Exception
Traceback (most recent call last):
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 368, in _process_open_vuln
    i = self._jira.issues.upsert(fields=issue, jql=' and '.join(jql))
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 48, in upsert
    issue = self.create(**kwargs)
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/jira/issues.py", line 20, in create
    json=kwargs
  File "/root/tenablejira/lib64/python3.6/site-packages/restfly/session.py", line 563, in post
    return self._request('POST', path, **kwargs)
  File "/root/tenablejira/lib64/python3.6/site-packages/restfly/session.py", line 477, in _request
    raise err(resp, retries=retries, func=self._error_func)
restfly.errors.BadRequestError: [400: POST] https://<JIRA_CLOUD_HOST>/rest/api/3/issue?update_history=False body=b'{"errorMessages":["We can\'t create this issue for you right now, it could be due to unsupported content you\'ve entered into one or more of the issue fields. If this situation persists, contact your administrator as they\'ll be able to access more specific information in the log file."],"errors":{}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 151, in cli
    ingest.ingest(observed_since)
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 688, in ingest
    self.create_issues(vulns)
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 488, in create_issues
    self._process_open_vuln(v, fid)
  File "/root/tenablejira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 371, in _process_open_vuln
    sys.exit(2)
SystemExit: 2
```

Then another trigger to obtain the debug log.
`tenable-jira generated_config.yaml --troubleshoot`

The ID for Task and Sub-Task - they are indeed 10002 and 10003 respectively.

Please find the latest debug log here: 
[issue_debug.zip](https://github.com/tenable/integration-jira-cloud/files/5818912/issue_debug.zip)

**Comment by SteveMcGrath** [comment]
Typical useless Jira error messages.  can you check your query in SC and make sure that informational plugins are not selected?

**Comment by SteveMcGrath** [comment]
Closing due to lack of response.
